apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::200504912460:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-154TIV7GJKYWW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::200504912460:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T13:37:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4950"
  uid: 2b0f166c-efc8-4df4-91ac-f902d1f0578e
